### ISSUE TITLE
TypeError: cannot pickle 'LogicalReplicationConnection' object

### ISSUE THREAD

**Issue by gunnarmorling** [dgea005/pypgoutput#22]
When trying to run the snippet from the README, I am getting the following error:

```
Traceback (most recent call last):
  File "/Users/gunnarmorling/Development/pgoutput-cli/test.py", line 11, in <module>
    cdc_reader = pypgoutput.LogicalReplicationReader(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gunnarmorling/Development/pgoutput-cli/.venv/lib/python3.12/site-packages/pypgoutput/reader.py", line 138, in __init__
    self.setup()
  File "/Users/gunnarmorling/Development/pgoutput-cli/.venv/lib/python3.12/site-packages/pypgoutput/reader.py", line 146, in setup
    self.extractor.start()
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'LogicalReplicationConnection' object
```

My Python-foo is quite limited, it seems this somehow is related to serializing this object? Would would that happen though? Thanks for any advice!

**Comment by gunnarmorling** [comment]
Note I have used _pypgoutput_ successfully in the past. If I had to guess, I'd say this may be caused by a change in this underlying library _psycopg2_?

**Comment by yaoqi** [comment]
@gunnarmorling I encountered the same issue, and extracting the part of the framework that parses the message resolved the problem in my project.
